import { TrackType } from './sharedTypes/sharedTypes';

export const data: TrackType[] = [
  {
    _id: 1,
    name: 'Guilt',
    author: 'Nero',
    release_date: '2011-05-12',
    genre: ['Drum & Bass'],
    duration_in_seconds: 192,
    album: 'Welcome Reality',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 2,
    name: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    release_date: '2018-03-15',
    genre: ['Electro House'],
    duration_in_seconds: 174,
    album: 'Elektro',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 3,
    name: "I'm Fire",
    author: 'Ali Bakgor',
    release_date: '2020-01-20',
    genre: ['Deep House'],
    duration_in_seconds: 156,
    album: "I'm Fire",
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 4,
    name: 'Non Stop',
    author: 'Стоункат, Psychopath',
    release_date: '2015-07-10',
    genre: ['Rock'],
    duration_in_seconds: 223,
    album: 'Non Stop',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 5,
    name: 'Run Run',
    author: 'Jaded, Will Clarke, AR/CO',
    release_date: '2017-09-05',
    genre: ['Techno'],
    duration_in_seconds: 203,
    album: 'Run Run',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 6,
    name: 'Eyes on Fire',
    author: 'Blue Foundation, Zeds Dead',
    release_date: '2013-11-18',
    genre: ['Dubstep'],
    duration_in_seconds: 195,
    album: 'Eyes on Fire',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 7,
    name: 'Mucho Bien',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    release_date: '2019-04-22',
    genre: ['Disco House'],
    duration_in_seconds: 168,
    album: 'Mucho Bien',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 8,
    name: 'Knives n Cherries',
    author: 'minthaze',
    release_date: '2021-02-14',
    genre: ['Chillout'],
    duration_in_seconds: 210,
    album: 'Captivating',
    logo: null,
    track_file: '',
    stared_user: [],
  },
  {
    _id: 9,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    _id: 10,
    name: 'Open Sea epic',
    author: 'Frank Schroter',
    release_date: '2019-06-12',
    genre: ['Классическая музыка'],
    duration_in_seconds: 165,
    album: 'Open Sea epic',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Frank_Schroter_-_Open_Sea_epic.mp3',
    stared_user: [],
  },
  {
    _id: 11,
    name: 'Sneaky Snitch',
    author: 'Kevin Macleod',
    release_date: '2022-04-16',
    genre: ['Классическая музыка'],
    duration_in_seconds: 305,
    album: 'Sneaky Snitch',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_Macleod_-_Sneaky_Snitch.mp3',
    stared_user: [],
  },
  {
    _id: 12,
    name: 'Secret Garden',
    author: 'Mixkit',
    release_date: '1972-06-06',
    genre: ['Классическая музыка'],
    duration_in_seconds: 324,
    album: 'Secret Garden',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Mixkit_-_Secret_Garden.mp3',
    stared_user: [],
  },

  {
    _id: 13,
    name: 'A journey of successfull winners',
    author: '-',
    release_date: '1985-02-02',
    genre: ['Классическая музыка'],
    duration_in_seconds: 255,
    album: '-',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_A_Journey_For_Successful_Winners.mp3',
    stared_user: [],
  },
  {
    _id: 14,
    name: 'Epic Heroic Conquest',
    author: '-',
    release_date: '1962-01-15',
    genre: ['Классическая музыка'],
    duration_in_seconds: 200,
    album: 'Epic Heroic Conquest',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_Epic_Heroic_Conquest.mp3',
    stared_user: [],
  },
  {
    _id: 15,
    name: 'The March OF The Final Battle',
    author: '-',
    release_date: '2011-11-02',
    genre: ['Классическая музыка'],
    duration_in_seconds: 206,
    album: 'The March OF The Final Battle',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/musiclfiles_-_The_March_Of_The_Final_Battle.mp3',
    stared_user: [],
  },
  {
    _id: 16,
    name: 'True Summer',
    author: '-',
    release_date: '2012-06-01',
    genre: ['Классическая музыка'],
    duration_in_seconds: 253,
    album: 'True Summer',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_True_Summer.mp3',
    stared_user: [],
  },
  {
    _id: 17,
    name: 'Background Sensible',
    author: 'Waltz Piano',
    release_date: '2003-05-12',
    genre: ['Классическая музыка'],
    duration_in_seconds: 135,
    album: 'Background Sensible',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Waltz_Piano_-_Background_Sensible.mp3',
    stared_user: [],
  },
  {
    _id: 18,
    name: 'Cinematic',
    author: 'Winniethemoog',
    release_date: '2004-10-01',
    genre: ['Классическая музыка'],
    duration_in_seconds: 206,
    album: 'Cinematic',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Winniethemoog_-_Action_Sport_Breakbeat.mp3',
    stared_user: [],
  },
];
